services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: ecommerce_db
      POSTGRES_USER: e_user
      POSTGRES_PASSWORD: e_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U e_user -d ecommerce_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: