# Profil actif par défaut
mp.config.profile=dev

# Configuration commune
app.seeding.enabled=false

# Configuration spécifique au profil 'dev'
%dev.app.seeding.enabled=true
%dev.DB_URL=jdbc:postgresql://postgres:5432/ecommerce_db
%dev.DB_USER=e_user
%dev.DB_PASSWORD=e_password

# Configuration spécifique au profil 'test'
%test.app.seeding.enabled=true
%test.DB_URL=jdbc:postgresql://localhost:5432/ecommerce_test
